package com.driverUtility;

import io.cucumber.plugin.EventListener;
import io.cucumber.plugin.event.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Custom Cucumber Plugin to track test execution statistics for Maven Surefire
 * This helps resolve the "Tests run: 0" issue in Maven reporting
 */
public class CucumberTestCounterPlugin implements EventListener {
    private static final Logger logger = LoggerFactory.getLogger(CucumberTestCounterPlugin.class);
    
    private int totalScenarios = 0;
    private int passedScenarios = 0;
    private int failedScenarios = 0;
    private int totalSteps = 0;
    private int passedSteps = 0;
    private int failedSteps = 0;
    private int skippedSteps = 0;
    
    public CucumberTestCounterPlugin() {
        logger.info("CucumberTestCounterPlugin initialized");
    }
    
    @Override
    public void setEventPublisher(EventPublisher publisher) {
        publisher.registerHandlerFor(TestCaseFinished.class, this::handleTestCaseFinished);
        publisher.registerHandlerFor(TestStepFinished.class, this::handleTestStepFinished);
        publisher.registerHandlerFor(TestRunFinished.class, this::handleTestRunFinished);
    }
    
    private void handleTestCaseFinished(TestCaseFinished event) {
        totalScenarios++;
        
        Status status = event.getResult().getStatus();
        if (status == Status.PASSED) {
            passedScenarios++;
        } else if (status == Status.FAILED) {
            failedScenarios++;
        }
    }
    
    private void handleTestStepFinished(TestStepFinished event) {
        // Only count pickle steps (not hooks)
        if (event.getTestStep() instanceof PickleStepTestStep) {
            totalSteps++;
            
            Status status = event.getResult().getStatus();
            if (status == Status.PASSED) {
                passedSteps++;
            } else if (status == Status.FAILED) {
                failedSteps++;
            } else if (status == Status.SKIPPED) {
                skippedSteps++;
            }
        }
    }
    
    private void handleTestRunFinished(TestRunFinished event) {
        logger.info("═══════════════════════════════════════════════════════════════════");
        logger.info("                   TEST EXECUTION SUMMARY                           ");
        logger.info("═══════════════════════════════════════════════════════════════════");
        logger.info("Total Scenarios Executed: {}", totalScenarios);
        logger.info("  ✓ Passed: {}", passedScenarios);
        logger.info("  ✗ Failed: {}", failedScenarios);
        logger.info("Total Steps Executed: {}", totalSteps);
        logger.info("  ✓ Passed: {}", passedSteps);
        logger.info("  ✗ Failed: {}", failedSteps);
        logger.info("  ⊘ Skipped: {}", skippedSteps);
        logger.info("═══════════════════════════════════════════════════════════════════");
        
        // Write summary to file for Maven integration
        writeSummaryFile();
    }
    
    private void writeSummaryFile() {
        File reportDir = new File("target/cucumber-reports");
        if (!reportDir.exists()) {
            reportDir.mkdirs();
        }
        
        File summaryFile = new File(reportDir, "test-execution-summary.txt");
        try (PrintWriter writer = new PrintWriter(new FileWriter(summaryFile))) {
            writer.println("═══════════════════════════════════════════════════════════════════");
            writer.println("              CUCUMBER TEST EXECUTION SUMMARY (ECI India)          ");
            writer.println("═══════════════════════════════════════════════════════════════════");
            writer.println("Total Scenarios: " + totalScenarios);
            writer.println("Passed Scenarios: " + passedScenarios);
            writer.println("Failed Scenarios: " + failedScenarios);
            writer.println("Total Steps: " + totalSteps);
            writer.println("Passed Steps: " + passedSteps);
            writer.println("Failed Steps: " + failedSteps);
            writer.println("Skipped Steps: " + skippedSteps);
            writer.println("═══════════════════════════════════════════════════════════════════");
            writer.println();
            writer.println("NOTE: Maven Surefire may show 'Tests run: 0' due to Cucumber/JUnit");
            writer.println("Platform integration limitations. However, " + totalScenarios + " scenarios and");
            writer.println(totalSteps + " steps were actually executed as shown above.");
            writer.println();
            writer.println("Report Generated By: ECI India QA Team");
            
            logger.info("✓ Test execution summary written to: {}", summaryFile.getAbsolutePath());
        } catch (IOException e) {
            logger.error("Error writing test summary file: {}", e.getMessage());
        }
    }
}

